exchange/urls.py
from offers import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.urls import path, re_path
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('new', views.new),
    path('new', views.CreateOfferView.as_view(), name='create_offer'),
    # path('offers', views.show, name='offers'),
    path('offers', views.UserOfferView.as_view(), name='offers'),
    path('bids', views.UserBidsView.as_view(), name='bids'),
    # path('', views.showall, name='home'),
    path('', views.ShowOffersView.as_view(), name='home'),

    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$',
            auth_views.LoginView.as_view(template_name='jinja/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(r'^reset/$',
            auth_views.PasswordResetView.as_view(
                template_name='jinja/password_reset.html',
                email_template_name='jinja/password_reset_email.html',
                subject_template_name='jinja/password_reset_subject.txt'
            ),
            name='password_reset'),
    re_path(r'^reset/done/$',
            auth_views.PasswordResetDoneView.as_view(
                template_name='jinja/password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='jinja/password_reset_confirm.html'),
            name='password_reset_confirm'),
    re_path(r'^reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(
                template_name='jinja/password_reset_complete.html'),
            name='password_reset_complete'),

    re_path(r'^settings/account/$',
            accounts_views.update_profile, name='my_account'),
    re_path(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='jinja/password_change.html'),
            name='password_change'),
    re_path(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='jinja/password_change_done.html'),
            name='password_change_done'),
    
    re_path(r'offer/(?P<id>\d+)/$', views.BidListView.as_view(), name='view_bids'),
    re_path(r'offerbids/(?P<id>\d+)/$',
            views.UserOfferBidListView.as_view(), name='offer_bids'),
    re_path(r'offer/(?P<id>\d+)/new/$',
            views.CreateBidView.as_view(), name='new_bid'),
    re_path(r'bid/(?P<bid_id>\d+)/edit/$',
            views.BidUpdateView.as_view(), name='edit_bid'),
    # path('edit/<int:id>', views.PostUpdateView.as_view()),
    path('update/<int:id>', views.OfferUpdateView.as_view(), name='update_offer'),
    # path('delete/<int:id>', views.destroy),
    path('accept/<int:id>', views.OwnerAcceptBid, name='accept_bid'),
    path('decline/<int:id>', views.OwnerDeclineBid, name='decline_bid'),
    path('delete/<int:id>', views.OfferDeleteView.as_view(), name='delete_offer'),
    re_path(r'bid/delete/(?P<id>\d+)/$', views.BidDeleteView.as_view(), name='delete_bid'),
]

handler404 = 'offers.views.error_404_view'

offers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.utils.translation import gettext_lazy as _
from django import forms
# Create your models here.


class Offers(models.Model):
    CURRENCY = (
        ('USD', 'USD'),
        ('EUR', 'EUR'),
        ('GBP', 'GBP'),
    )
    METHOD_PAY = (
        ('Amazon Gift Card', 'Amazon Gift Card'),
        ('Paypal', 'PayPal'),
        ('Walmart Gift Card', 'Walmart Gift Card'),)
    fiat_currency = models.CharField(
        max_length=3, choices=CURRENCY, default=CURRENCY[0][0])
    pay_method = models.CharField(
        max_length=50, choices=METHOD_PAY, default=METHOD_PAY[0][0])
    min_amount = models.DecimalField(max_digits=36, decimal_places=18, validators=[
        MinValueValidator(Decimal('0.000000000000000001'), message="Ensure this value is greater than or equal to 0.000000000000000001.")])
    max_amount = models.DecimalField(max_digits=36, decimal_places=18, validators=[
        MinValueValidator(Decimal('0.000000000000000001'), message="Ensure this value is greater than or equal to 0.000000000000000001.")])
    margin_percent = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(100)])
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='offers')

    class Meta:
        db_table = "offers"

    def validate_min_amount(self):
        if self.min_amount > self.max_amount:
            raise ValidationError([
                {NON_FIELD_ERRORS: _("Minimum amount can't be greater than Maximum amount")}])
        if self.min_amount == self.max_amount:
            raise ValidationError([
                {NON_FIELD_ERRORS: _("Minimum amount can't be equal to Maximum amount")}])


class Bids(models.Model):
    STATES = (
        ('OPEN', 'OPEN'),
        ('ACCEPTED', 'ACCEPTED'),
        ('DECLINED', 'DECLINED'),
    )
    amount = models.DecimalField(max_digits=36, decimal_places=18, validators=[
        MinValueValidator(Decimal('0.000000000000000001'), message="Ensure this value is greater than or equal to 0.000000000000000001.")])
    offer = models.ForeignKey(
        Offers, on_delete=models.CASCADE, related_name='bids')
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bids')
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(null=True)
    status = models.CharField(
        max_length=8, choices=STATES, default=STATES[0][0])

    class Meta:
        db_table = "bids"

    # def clean(self):
    #     self.offer =
    #     if self.amount > self.offer.max_amount:
    #         raise ValidationError(
    #             {'amount': _("Bid can't be greater than {}".format(self.offer.max_amount))})
    #     if self.amount < self.offer.min_amount:
    #         raise ValidationError(
    #             {'amount': _("Bid can't be less than {}".format(self.offer.min_amount))})

    def validate_amount(self):
        if self.amount > self.offer.max_amount:
            raise ValidationError([
                {NON_FIELD_ERRORS: _("Bid can't be greater than {}".format(self.offer.max_amount))}])
        if self.amount < self.offer.min_amount:
            raise ValidationError([
                {NON_FIELD_ERRORS: _("Bid can't be less than {}".format(self.offer.min_amount))}])

offers/forms.py
from django import forms
from offers.models import Offers


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offers
        # fields = "__all__"
        fields = ['fiat_currency', 'pay_method',
                  'min_amount', 'max_amount', 'margin_percent']

offers/views.py
from django.http import Http404
# from django.forms.util import ErrorList
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from django.utils import timezone
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect, reverse, HttpResponseRedirect
from django.urls import reverse_lazy
# Create your views here.
from offers.forms import OfferForm
from accounts.models import Accounts
from offers.models import Offers, Bids
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, ListView, CreateView, DeleteView
import requests
from decimal import Decimal
TICKER_API_URL = 'http://api.coinmarketcap.com/v1/ticker/'
# Create your views here.


def error_404_view(request, exception):
    return render(request, 'jinja/error_404.html')


@method_decorator(login_required, name='dispatch')
class OfferUpdateView(UpdateView):
    model = Offers
    fields = ('fiat_currency', 'pay_method',
              'min_amount', 'max_amount', 'margin_percent')
    template_name = 'jinja/edit.html'
    pk_url_kwarg = 'id'
    context_object_name = 'offer'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        price = round(get_latest_crypto_price('ethereum'))
        context['price'] = "The price of 1 ethereum is ${}".format(price)
        return context

    def form_valid(self, form):
        offer = form.save(commit=False)
        try:
            offer.validate_min_amount()
        except ValidationError as e:
            form.add_error('min_amount', e)
            return self.form_invalid(form)
        # post.updated_by = self.request.user
        # post.updated_at = timezone.now()
        offer.save()
        return redirect('offers')


@method_decorator(login_required, name='dispatch')
class CreateOfferView(CreateView):
    model = Offers
    fields = ['fiat_currency', 'pay_method',
              'min_amount', 'max_amount', 'margin_percent']
    template_name = 'jinja/index.html'

    def get_initial(self):
        acc = get_object_or_404(Accounts, owned_by=self.request.user)
        if acc.acc_balance == 0:
            raise Http404("Not enough Balance")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        price = round(get_latest_crypto_price('ethereum'))
        context['price'] = "The price of 1 ethereum is ${}".format(price)
        return context

    def form_valid(self, form):
        offer = form.save(commit=False)
        try:
            offer.validate_min_amount()
        except ValidationError as e:
            form.add_error('min_amount', e)
            return self.form_invalid(form)
        offer.created_by = self.request.user
        offer.save()
        return redirect('offers')


@method_decorator(login_required, name='dispatch')
class CreateBidView(CreateView):
    model = Bids
    fields = ['amount']
    template_name = 'jinja/add_bid.html'

    def get_initial(self):
        offer = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        if offer.created_by == self.request.user:
            raise Http404("Offer Owner can't create Bids")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['offer'] = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        feed = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        price = round(get_latest_crypto_price('ethereum'))
        context['price'] = "The price of 1 ethereum is ${}".format(price)
        context['warn'] = "The amount should be within the range of {} and {}".format(feed.min_amount, feed.max_amount)
        return context

    def form_valid(self, form):
        self.offer = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        bid = form.save(commit=False)
        bid.created_by = self.request.user
        bid.offer = self.offer
        try:
            bid.validate_amount()
        except ValidationError as e:
            form.add_error('amount',e)
            return self.form_invalid(form)
        bid.last_updated = timezone.now()
        bid.save()
        acc = get_object_or_404(Accounts, owned_by=self.offer.created_by)
        acc.escrow_balance += bid.amount
        acc.acc_balance -= bid.amount
        acc.save()
        return redirect('view_bids', id=self.offer.pk)


@method_decorator(login_required, name='dispatch')
class BidUpdateView(UpdateView):
    model = Bids
    fields = ('amount',)
    template_name = 'jinja/edit_bid.html'
    pk_url_kwarg = 'bid_id'
    context_object_name = 'bid'

    def get_object(self, *args, **kwargs):
        bid = super(BidUpdateView, self).get_object(*args, **kwargs)
        if bid.status != "OPEN":
            raise Http404("No bids found matching the query")
        return bid

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        feed = get_object_or_404(Bids, pk=self.kwargs.get('bid_id'))
        context['warn'] = "The amount should be within the range of {} and {}".format(feed.offer.min_amount, feed.offer.max_amount)
        price = round(get_latest_crypto_price('ethereum'))
        context['price'] = "The price of 1 ethereum is ${}".format(price)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        bid = form.save(commit=False)
        try:
            bid.validate_amount()
        except ValidationError as e:
            form.add_error('amount', e)
            return self.form_invalid(form)
        bid.last_updated = timezone.now()
        bid.save()
        return redirect('view_bids', id=bid.offer.pk)

@method_decorator(login_required, name='dispatch')
class BidDeleteView(DeleteView):
    model = Bids
    pk_url_kwarg = 'id'
    # success_url = reverse_lazy('offers')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def delete(self, request, *args, **kwargs):
        # pk = self.kwargs['pk']
        self.bid = get_object_or_404(Bids, pk=self.kwargs.get('id'))
        if self.bid.created_by != self.request.user:
            raise Http404("No bids found matching the query")
        if self.bid.status == "ACCEPTED":
            raise Http404("No bids found matching the query")
        if self.bid.status == "OPEN":
            acc = get_object_or_404(Accounts, owned_by=self.bid.offer.created_by)
            acc.escrow_balance -= self.bid.amount
            acc.acc_balance += self.bid.amount
            acc.save()
        pk = self.bid.offer.pk
        self.bid.delete()
        return HttpResponseRedirect(reverse('view_bids', kwargs={'id': pk}))

@login_required
def OwnerAcceptBid(request, id):
    bid = get_object_or_404(Bids, pk=id)
    if bid.offer.created_by != request.user:
        raise Http404("No bids found matching the query")
    if bid.status != "OPEN":
        raise Http404("No bids found matching the query")
    acc = get_object_or_404(Accounts, owned_by=request.user)
    if acc.acc_balance == 0:
        raise Http404("Not enough Balance")
    pk = bid.offer.pk
    # margin = bid.offer.margin_percent
    bid_amount = bid.amount
    acc2 = get_object_or_404(Accounts, owned_by=bid.created_by)
    # price = round(get_latest_crypto_price('ethereum'))
    # amount = bid_amount / (price * (margin + 100))
    acc.escrow_balance -= bid_amount
    acc.save()
    acc2.acc_balance += bid_amount
    acc2.save()
    bid.status = "ACCEPTED"
    bid.save()
    return HttpResponseRedirect(reverse('view_bids', kwargs={'id': pk}))

@login_required
def OwnerDeclineBid(request, id):
    bid = get_object_or_404(Bids, pk=id)
    if bid.offer.created_by != request.user:
        raise Http404("No bids found matching the query")
    if bid.status != "OPEN":
        raise Http404("No bids found matching the query")
    acc = get_object_or_404(Accounts, owned_by=request.user)
    acc.escrow_balance -= bid.amount
    acc.acc_balance += bid.amount
    acc.save()
    pk = bid.offer.pk
    bid.status = "DECLINED"
    bid.save()
    return HttpResponseRedirect(reverse('view_bids', kwargs={'id': pk}))

# @method_decorator(login_required, name='dispatch')
class BidListView(ListView):
    model = Bids
    context_object_name = 'bids'
    template_name = 'jinja/bids.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['price'] = round(get_latest_crypto_price('ethereum'))
        kwargs['offer'] = self.offer
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.offer = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        queryset = self.offer.bids.order_by('-last_updated')
        return queryset

@method_decorator(login_required, name='dispatch')
class UserOfferBidListView(ListView):
    model = Bids
    context_object_name = 'bids'
    template_name = 'jinja/offer_bids.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['price'] = round(get_latest_crypto_price('ethereum'))
        kwargs['offer'] = self.offer
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.offer = get_object_or_404(Offers, pk=self.kwargs.get('id'))
        if self.offer.created_by != self.request.user:
            raise Http404("No offers found matching the query")
        queryset = self.offer.bids.order_by('-last_updated')
        return queryset

@method_decorator(login_required, name='dispatch')

templates/jinja/add_bid.html
{% extends 'jinja/base.html' %}
{% block title %}Make Bid{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{{ static('css/style.css') }}" />
<link rel="stylesheet" href="{{ static('css/bootstrap.min.css') }}" />
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb my-4 bg-dark">
    <li class="breadcrumb-item"><a href="{{ url('home') }}" class="text-white">Offers</a></li>
    <li class="breadcrumb-item text-white"><a href="/offer/{{ offer.pk }}" class="text-white"> Offer Bids</a></li>
    <li class="breadcrumb-item active text-white">Make New Bid</li>
</ol>
{% endblock %}

{% block content %}
<div class="alert alert-primary" role="alert">
    {{ warn }}
</div>
<div class="alert alert-primary" role="alert" id="test">
    {{ price }}
</div>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="POST" class="post-form" novalidate>
            {{ csrf_input }}
            {% if form.non_field_errors() %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors() %}
                <p{% if loop.last %} class="mb-0" {% endif %}>{{ error }}</p>
                    {% endfor %}
            </div>
            {% endif %}
            <div class="form-row">
                <label for="id_amount" class=" requiredField">
                    Amount<span class="asteriskField">*</span>
                </label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend" style="height: 38px;">
                        <div class="input-group-text">ETH</div>
                    </div>
                    {{ as_crispy_field(form.amount, label_class="sr-only", field_class="") }}
                </div>
            </div>
            <div class="alert alert-warning" style="display:none;" id="tester">
                <strong id="report"></strong>
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
            <a href="/offer/{{ offer.pk }}" class="btn btn-outline-secondary" role="button">Cancel</a>
        </form>
    </div>
</div>
<script>
    let btc_amount = document.getElementById("id_amount");
    let err = document.getElementById("report");
    let test = document.getElementById("test");
    let tester = document.getElementById("tester");

    btc_amount.addEventListener("input", function () {
        tester.style.display = "block";
        let text = test.textContent;
        let pr = Number(text.split("$")[1])
        let res = btc_amount.value * pr;
        err.innerHTML = btc_amount.value + " ETH = $" + res;
    });
</script>
{% endblock %}

templates/jinja/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Xchange{% endblock %}</title>
    <link rel="stylesheet" href="{{ static('css/bootstrap.min.css') }}">
    {% block stylesheet %}{% endblock %}
</head>

<body>
    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url('home') }}">Xchange</a>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class={% if request.path == '/offers' %} "nav-item active" {% endif %}>
                    <a class="nav-link" href="{{ url('offers') }}">My Offers {% if request.path == '/offers' %}<span
                            class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class={% if request.path == '/bids' %} "nav-item active" {% endif %}>
                    <a class="nav-link" href="{{ url('bids') }}">My Bids {% if request.path == '/bids' %}<span
                            class="sr-only">(current)</span>{% endif %} </a>
                </li>
                <li class={% if request.path == '/' %} "nav-item active" {% endif %}>
                    <a class="nav-link" href="{{ url('home') }}">All Offers {% if request.path == '/' %}<span
                            class="sr-only">(current)</span>{% endif %} </a>
                </li>
                {% else %}
                <li class={% if request.path == '/' %} "nav-item active" {% endif %}>
                    <a class="nav-link" href="{{ url('home') }}">All Offers
                        {% if request.path == '/' %}<span class="sr-only">(current)</span>{% endif %}
                    </a>
                </li>
                {% endif %}
            </ul>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{{ url('my_account') }}">My account</a>
                            <a class="dropdown-item" href="{{ url('password_change') }}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url('logout') }}">Log out</a>
                        </div>
                    </li>
                </ul>
                {% else %}
                <form class="form-inline ml-auto">
                    <a href="{{ url('login') }}" class="btn btn-outline-secondary">Log in</a>
                    <a href="{{ url('signup') }}" class="btn btn-primary ml-2">Sign up</a>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>


    <div class="container">

        {% block breadcrumb %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>
    {% endblock %}
    <script src="{{ static('js/jquery-3.4.1.js') }}"></script>
    <script src="{{ static('js/popper.min.js') }}"></script>
    <script src="{{ static('js/bootstrap.min.js') }}"></script>
</body>

</html>

templates/jinja/edit_bid.html
{% extends 'jinja/base.html' %}
{% block title %}Update Bid{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{{ static('css/style.css') }}" />
<link rel="stylesheet" href="{{ static('css/bootstrap.min.css') }}" />
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb my-4 bg-dark">
    <li class="breadcrumb-item"><a href="{{ url('home') }}" class="text-white">Offers</a></li>
    <li class="breadcrumb-item text-white"><a href="/offer/{{ bid.offer.pk }}" class="text-white"> Offer Bids</a></li>
    <li class="breadcrumb-item active text-white">Edit Bid</li>
</ol>
{% endblock %}

{% block content %}
<div class="alert alert-primary" role="alert">
    {{ warn }}
</div>
<div class="alert alert-primary" role="alert" id="test">
    {{ price }}
</div>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="POST" class="post-form" action="/bid/{{bid.id}}/edit/" novalidate>
            {{ csrf_input }}
            {% if form.non_field_errors() %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors() %}
                <p{% if loop.last %} class="mb-0" {% endif %}>{{ error }}</p>
                    {% endfor %}
            </div>
            {% endif %}
            <div class="form-row">
                <label for="id_amount" class=" requiredField">
                    Amount<span class="asteriskField">*</span>
                </label>
                <div class="input-group mb-2">
                    <div class="input-group-prepend" style="height: 38px;">
                        <div class="input-group-text">ETH</div>
                    </div>
                    {{ as_crispy_field(form.amount, label_class="sr-only", field_class="") }}
                </div>
            </div>
            <div class="alert alert-warning" id="tester">
                <strong id="report"></strong>
            </div>
            <button type="submit" class="btn btn-success">Save changes</button>
            <a href="/offer/{{ bid.offer.pk }}" class="btn btn-outline-secondary" role="button">Cancel</a>
        </form>
    </div>
</div>
<script>
    //let doc = document.getElementsByTagName("BODY")[0];
    let btc_amount = document.getElementById("id_amount");
    let err = document.getElementById("report");
    let test = document.getElementById("test");
    let tester = document.getElementById("tester");

    document.addEventListener("readystatechange", function () {
        tester.style.display = "block";
        let text = test.textContent;
        let pr = Number(text.split("$")[1])
        let res = btc_amount.value * pr;
        err.innerHTML = btc_amount.value + " ETH = $" + res;
    });
    btc_amount.addEventListener("input", function () {
        tester.style.display = "block";
        let text = test.textContent;
        let pr = Number(text.split("$")[1])
        let res = btc_amount.value * pr;
        err.innerHTML = btc_amount.value + " ETH = $" + res;
    });
</script>
{% endblock %}

templates/jinja/my_account.html
{% extends 'jinja/base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumbb %}
<li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb my-4 bg-dark">
    <li class="breadcrumb-item active text-white">My account</li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post" novalidate>
            {{ csrf_input }}
            {% if user_form.non_field_errors() %}
            <div class="alert alert-danger" role="alert">
                {% for error in user_form.non_field_errors() %}
                <p{% if loop.last %} class="mb-0" {% endif %}>{{ error }}</p>
                    {% endfor %}
            </div>
            {% endif %}

            {% for field in user_form %}
            <div class="form-group">
                {{ as_crispy_field(field) }}
            </div>
            {% endfor %}
            {% if profile_form.non_field_errors() %}
            <div class="alert alert-danger" role="alert">
                {% for error in profile_form.non_field_errors() %}
                <p{% if loop.last %} class="mb-0" {% endif %}>{{ error }}</p>
                    {% endfor %}
            </div>
            {% endif %}

            {% for field in profile_form %}
            <div class="form-group">
                {{ as_crispy_field(field) }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Save changes</button>
        </form>
    </div>
</div>
{% endblock %}

templates/jinja/password_change.html
{% extends 'jinja/base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumbb %}
<li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb my-4 bg-dark">
    <li class="breadcrumb-item active text-white">Change password</li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post" novalidate>
            {{ csrf_input }}
            {% include 'jinja/includes/form.html' %}
            <button type="submit" class="btn btn-success">Change password</button>
        </form>
    </div>
</div>
{% endblock %}